QUOTES = [
    ("GET BACK\nTO WORK", "Your future self is watching.\nAnd they're disgusted."),
    ("REALLY?", "You picked up your phone again.\nIncredible."),
    ("PUT IT\nDOWN.", "Right now. I'm serious."),
    ("YOUR COMPETITION\nISN'T ON INSTAGRAM", "Just saying."),
    ("EVERY SECOND\nCOUNTS", "You just wasted three of them."),
    ("NO.", "Not now. Not ever during work hours."),
    ("THE GRAVEYARD IS FULL\nOF PEOPLE", "who said 'just one more scroll.'"),
    ("YOU WERE\nSO CLOSE", "23 minutes without touching it.\nNow look at you."),
    ("THAT DOPAMINE HIT\nISN'T WORTH IT", "Lock in."),
    ("WHAT ARE YOU\nEVEN LOOKING FOR?", "Put it face down and get back to work."),
    ("YOUR GOALS\nWON'T CHASE THEMSELVES", "The phone will still be there in 2 hours."),
    ("BREAKING NEWS:", "Your tweets can wait."),
    ("THIS IS WHY\nYOU'RE BEHIND", "Every. Single. Time."),
    ("FUTURE YOU\nIS ANGRY", "Past you is embarrassing future you right now."),
    ("THE BEST TIME\nTO PUT IT DOWN", "Was 5 minutes ago.\nThe second best time is now."),
    ("NOBODY IS\nTEXTING YOU", "anything that important. Put it down."),
    ("YOU'RE BETTER\nTHAN THIS", "Act like it."),
    ("ONE HOUR OF\nDEEP WORK", "is worth 4 hours of distracted work.\nChoose."),
    ("YOUR PHONE\nIS NOT YOUR FRIEND", "Right now it's your enemy. Treat it like one."),
    ("DO YOU WANT\nSUCCESS", "or do you want to scroll?\nPick one."),
    ("LOCK IN.", "That's the whole message."),
    ("DISCIPLINE IS\nREMEMBERING", "what you actually want.\nYou don't want the phone."),
    ("3... 2... 1...", "Put. It. Down."),
    ("IMAGINE HOW MUCH\nYOU COULD DO", "if you stopped picking this up.\nImagine it. Now do it."),
    ("THE WORK\nWON'T DO ITSELF", "And you won't do it while you're scrolling."),
    ("YOU HAVE GOALS.", "This isn't one of them."),
    ("NOT NOW.", "Focus. The phone isn't going anywhere."),
    ("SERIOUSLY?", "You just had a break.\nGet back to work."),
    ("CLOSE\nENOUGH TO SEE?", "Good. Now put it back down."),
    ("WINNERS DON'T\nDOOM SCROLL", "They just don't."),
]

VOICE_LINES = [
    "Put it down. Right now.",
    "Are you serious right now.",
    "You were doing so well.",
    "That phone is not your friend.",
    "Every second counts. Get back to work.",
    "Put. It. Down.",
    "Really? Again? Incredible.",
    "No. No no no. Put it down.",
    "Your future self is watching and they are not happy.",
    "Lock in. Come on.",
    "Not the phone. Not now.",
    "You just had a break. What are you doing.",
    "This is exactly why you're behind.",
    "Close. The. App.",
    "One scroll becomes ten. You know this.",
    "Get back to work. You can do this.",
    "The phone will survive without you for two hours.",
    "Discipline. Focus. Now.",
    "I see you. Put it down.",
    "Work now. Phone later. That's the deal.",
]
